version: "3"
services:
  app:
    container_name: zilla-final-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3301:3000
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./app:/app
    environment:
      - mongoUrl=mongodb://admin:secret@zilla-final-db:27017/pzfinal
    networks:
      - pzfinal
    env_file:
      - ./app/.env
  db:
    container_name: zilla-final-db
    image: mongo:latest
    ports:
      - 27019:27017
    restart: unless-stopped

    volumes:
      - ./docker/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    networks:
      - pzfinal
networks:
  pzfinal:
