name: "Build and push to dockerhub"

on:
  push:
    branches:
      - main
jobs:
  checking-nodejs:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: setup nodejs v18
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: install dependencies
        run: npm install

      - name: run application
        run: npm start&

      - name: test if app is working
        run: until curl -v http://localhost:3000  > /dev/null; do sleep 1; done

      - name: build docker images
        run: |
          docker build -t ilhamfadhilah/bootcamp-b4-docker:dev .

      - name: docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: push to dockerhub
        run: |
          docker push ilhamfadhilah/bootcamp-b4-docker:dev
